from scripts.common import parse_genomes_and_sequences

import os
import glob
import pathlib

configfile: os.path.join(workflow.basedir, "..", "config", "config.yaml")

# directory to raw reads
READDIR = config["reads_dir"]

# path to metadata
METADATA = config["genome_info"]

# directory to save the results
RESULTS_DIR = config["results_dir"]

# reads type
READS_TYPE = config["reads_type"]

# subsampled reads number
SUBREADS_COUNT = config["count"]

# convert number of subsampled read sets into a list of strings
NUMBER = ["{:02d}".format(i+1) for i in range(SUBREADS_COUNT)]

# get genome names and sequences path
if READS_TYPE == "hybrid":
    GENOME, SHORT_R1_MAP, SHORT_R2_MAP, LONG_READS_MAP = parse_genomes_and_sequences(READS_TYPE, METADATA, READDIR)

if READS_TYPE == "short":
    GENOME, SHORT_R1_MAP, SHORT_R2_MAP = parse_genomes_and_sequences(READS_TYPE, METADATA, READDIR)
    
if READS_TYPE == "long":
    GENOME, LONG_READS_MAP = parse_genomes_and_sequences(READS_TYPE, METADATA, READDIR)

# conda_envs for tracking plassembler_db
CONDA_ENVS = config["conda_envs"]

# rules
include: "rules/setup.smk"
include: "rules/process.smk"

# funtion to define requested inputs for the rule all
def get_all_input(wildcards):
    wanted_input = []

    if config["reads_type"]=="short":
        wanted_input = short_only_input

    if config["reads_type"]=="long":
        wanted_input = long_only_input
    
    if config["reads_type"]=="hybrid":
        wanted_input = hybrid_input

    return wanted_input

# master target rule
rule all:
    input: get_all_input